name: durumi
description: An auto-reply bot for KakaoTalk.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.0
  dynamic_color: ^1.6.5
  google_fonts: ^4.0.5

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
